name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run
      run: nohup dotnet run --project TodoListApp.WebApp > /dev/null 2>&1 &
    - name: Verify server is up
      run: sleep 5 && curl -k -I https://127.0.0.1:5001/Account/Login
    - name: Test
      run: dotnet test --no-restore
