name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run
      run: nohup dotnet run --project TodoListApp.WebApp > /dev/null 2>&1 &
    - name: Wait until server is up
      run: curl -k -I --retry 10 --retry-connrefused --retry-delay 6 https://localhost:5001/Account/Login
    - name: Test
      run: dotnet test --no-restore
    - uses: actions/checkout@v2
      if: failure()
      with:
        name: test_screenshots
        path: /tmp/Screenshots/      
      
      
